### ISSUE TITLE
Help with my extra functionality

### ISSUE THREAD

**Issue by hcps-lujm** [NevillePurple/PurpleAmerica#23]
So I used the text function from the edu.princeton.cs.introtocs class to write all the states names, but some of the states repeat. How should I go about fixing this? I was thinking of doing it similar to our hangman project and using arraylists, but is there a better way? @walterspa @hcps-duongth

**Comment by walterspa** [comment]
I think ArrayLists are the best option. We can go over it in class.

**Comment by hcps-lujm** [comment]
okay sounds good
